name: Deploy to pages
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: "Volta: install node & npm"
        uses: volta-cli/action@v1.7.0

      - name: Cache npm cache
        uses: actions/cache@v2
        env:
          cache-name: cache-npm-cache
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: npm install
        run: npm install
        
      - name: Get Pages deploy path
        id: get_root_url
        run: |
          echo "::set-output name=root_path::${REPO#${{github.repository_owner}}}/"
          echo "::set-output name=deploy_url::https://${{github.repository_owner}}.github.io/${REPO#${{github.repository_owner}}}"
        env:
          REPO: ${{github.repository}}

      - name: ember build
        run: npm run build
        env:
          EMBER_ROOT_URL: ${{steps.get_root_url.outputs.root_path}}
          
      - name: Skip jekyll builds
        run: touch dist/.nojekyll

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: ember-dist
          path: dist

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: dist
